[package]
name = "form-validation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
printpdf = "0.6"
base64 = "0.21"
js-sys = "0.3"

[lib]
crate-type = ["cdylib", "rlib"]
